# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_lambdas

analyzer:
#   exclude:
#     - path/to/excluded/files/**
