name: pubx
description: The missing `pub` commands.
version: 1.0.0
author: Scott Hyndman <scotty.hyndman@gmail.com>
repository: https://github.com/shyndman/pubx

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.0
  http: ^0.12.0
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
